services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "(mysqladmin ping -u pingtest || exit 1) && sleep 1"]
      interval: 5s
      retries: 20
      start_interval: 5s
      start_period: 10s

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/workspace:cached
      # - /workspace/backend/vendor
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      retries: 30
      start_interval: 5s

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/workspace:cached
      - /workspace/frontend/node_modules
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_data:
